# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/test/tamagotchi

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/test/tamagotchi

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/test/tamagotchi/CMakeFiles /home/test/tamagotchi/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/test/tamagotchi/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tamagotchi

# Build rule for target.
tamagotchi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tamagotchi
.PHONY : tamagotchi

# fast build rule for target.
tamagotchi/fast:
	$(MAKE) -f CMakeFiles/tamagotchi.dir/build.make CMakeFiles/tamagotchi.dir/build
.PHONY : tamagotchi/fast

sources/button.o: sources/button.cpp.o
.PHONY : sources/button.o

# target to build an object file
sources/button.cpp.o:
	$(MAKE) -f CMakeFiles/tamagotchi.dir/build.make CMakeFiles/tamagotchi.dir/sources/button.cpp.o
.PHONY : sources/button.cpp.o

sources/button.i: sources/button.cpp.i
.PHONY : sources/button.i

# target to preprocess a source file
sources/button.cpp.i:
	$(MAKE) -f CMakeFiles/tamagotchi.dir/build.make CMakeFiles/tamagotchi.dir/sources/button.cpp.i
.PHONY : sources/button.cpp.i

sources/button.s: sources/button.cpp.s
.PHONY : sources/button.s

# target to generate assembly for a file
sources/button.cpp.s:
	$(MAKE) -f CMakeFiles/tamagotchi.dir/build.make CMakeFiles/tamagotchi.dir/sources/button.cpp.s
.PHONY : sources/button.cpp.s

sources/connexion.o: sources/connexion.cpp.o
.PHONY : sources/connexion.o

# target to build an object file
sources/connexion.cpp.o:
	$(MAKE) -f CMakeFiles/tamagotchi.dir/build.make CMakeFiles/tamagotchi.dir/sources/connexion.cpp.o
.PHONY : sources/connexion.cpp.o

sources/connexion.i: sources/connexion.cpp.i
.PHONY : sources/connexion.i

# target to preprocess a source file
sources/connexion.cpp.i:
	$(MAKE) -f CMakeFiles/tamagotchi.dir/build.make CMakeFiles/tamagotchi.dir/sources/connexion.cpp.i
.PHONY : sources/connexion.cpp.i

sources/connexion.s: sources/connexion.cpp.s
.PHONY : sources/connexion.s

# target to generate assembly for a file
sources/connexion.cpp.s:
	$(MAKE) -f CMakeFiles/tamagotchi.dir/build.make CMakeFiles/tamagotchi.dir/sources/connexion.cpp.s
.PHONY : sources/connexion.cpp.s

sources/draw.o: sources/draw.cpp.o
.PHONY : sources/draw.o

# target to build an object file
sources/draw.cpp.o:
	$(MAKE) -f CMakeFiles/tamagotchi.dir/build.make CMakeFiles/tamagotchi.dir/sources/draw.cpp.o
.PHONY : sources/draw.cpp.o

sources/draw.i: sources/draw.cpp.i
.PHONY : sources/draw.i

# target to preprocess a source file
sources/draw.cpp.i:
	$(MAKE) -f CMakeFiles/tamagotchi.dir/build.make CMakeFiles/tamagotchi.dir/sources/draw.cpp.i
.PHONY : sources/draw.cpp.i

sources/draw.s: sources/draw.cpp.s
.PHONY : sources/draw.s

# target to generate assembly for a file
sources/draw.cpp.s:
	$(MAKE) -f CMakeFiles/tamagotchi.dir/build.make CMakeFiles/tamagotchi.dir/sources/draw.cpp.s
.PHONY : sources/draw.cpp.s

sources/showBMP.o: sources/showBMP.cpp.o
.PHONY : sources/showBMP.o

# target to build an object file
sources/showBMP.cpp.o:
	$(MAKE) -f CMakeFiles/tamagotchi.dir/build.make CMakeFiles/tamagotchi.dir/sources/showBMP.cpp.o
.PHONY : sources/showBMP.cpp.o

sources/showBMP.i: sources/showBMP.cpp.i
.PHONY : sources/showBMP.i

# target to preprocess a source file
sources/showBMP.cpp.i:
	$(MAKE) -f CMakeFiles/tamagotchi.dir/build.make CMakeFiles/tamagotchi.dir/sources/showBMP.cpp.i
.PHONY : sources/showBMP.cpp.i

sources/showBMP.s: sources/showBMP.cpp.s
.PHONY : sources/showBMP.s

# target to generate assembly for a file
sources/showBMP.cpp.s:
	$(MAKE) -f CMakeFiles/tamagotchi.dir/build.make CMakeFiles/tamagotchi.dir/sources/showBMP.cpp.s
.PHONY : sources/showBMP.cpp.s

sources/sql.o: sources/sql.cpp.o
.PHONY : sources/sql.o

# target to build an object file
sources/sql.cpp.o:
	$(MAKE) -f CMakeFiles/tamagotchi.dir/build.make CMakeFiles/tamagotchi.dir/sources/sql.cpp.o
.PHONY : sources/sql.cpp.o

sources/sql.i: sources/sql.cpp.i
.PHONY : sources/sql.i

# target to preprocess a source file
sources/sql.cpp.i:
	$(MAKE) -f CMakeFiles/tamagotchi.dir/build.make CMakeFiles/tamagotchi.dir/sources/sql.cpp.i
.PHONY : sources/sql.cpp.i

sources/sql.s: sources/sql.cpp.s
.PHONY : sources/sql.s

# target to generate assembly for a file
sources/sql.cpp.s:
	$(MAKE) -f CMakeFiles/tamagotchi.dir/build.make CMakeFiles/tamagotchi.dir/sources/sql.cpp.s
.PHONY : sources/sql.cpp.s

sources/tamagotchi.o: sources/tamagotchi.cpp.o
.PHONY : sources/tamagotchi.o

# target to build an object file
sources/tamagotchi.cpp.o:
	$(MAKE) -f CMakeFiles/tamagotchi.dir/build.make CMakeFiles/tamagotchi.dir/sources/tamagotchi.cpp.o
.PHONY : sources/tamagotchi.cpp.o

sources/tamagotchi.i: sources/tamagotchi.cpp.i
.PHONY : sources/tamagotchi.i

# target to preprocess a source file
sources/tamagotchi.cpp.i:
	$(MAKE) -f CMakeFiles/tamagotchi.dir/build.make CMakeFiles/tamagotchi.dir/sources/tamagotchi.cpp.i
.PHONY : sources/tamagotchi.cpp.i

sources/tamagotchi.s: sources/tamagotchi.cpp.s
.PHONY : sources/tamagotchi.s

# target to generate assembly for a file
sources/tamagotchi.cpp.s:
	$(MAKE) -f CMakeFiles/tamagotchi.dir/build.make CMakeFiles/tamagotchi.dir/sources/tamagotchi.cpp.s
.PHONY : sources/tamagotchi.cpp.s

sources/textinput.o: sources/textinput.cpp.o
.PHONY : sources/textinput.o

# target to build an object file
sources/textinput.cpp.o:
	$(MAKE) -f CMakeFiles/tamagotchi.dir/build.make CMakeFiles/tamagotchi.dir/sources/textinput.cpp.o
.PHONY : sources/textinput.cpp.o

sources/textinput.i: sources/textinput.cpp.i
.PHONY : sources/textinput.i

# target to preprocess a source file
sources/textinput.cpp.i:
	$(MAKE) -f CMakeFiles/tamagotchi.dir/build.make CMakeFiles/tamagotchi.dir/sources/textinput.cpp.i
.PHONY : sources/textinput.cpp.i

sources/textinput.s: sources/textinput.cpp.s
.PHONY : sources/textinput.s

# target to generate assembly for a file
sources/textinput.cpp.s:
	$(MAKE) -f CMakeFiles/tamagotchi.dir/build.make CMakeFiles/tamagotchi.dir/sources/textinput.cpp.s
.PHONY : sources/textinput.cpp.s

sources/timeleft.o: sources/timeleft.cpp.o
.PHONY : sources/timeleft.o

# target to build an object file
sources/timeleft.cpp.o:
	$(MAKE) -f CMakeFiles/tamagotchi.dir/build.make CMakeFiles/tamagotchi.dir/sources/timeleft.cpp.o
.PHONY : sources/timeleft.cpp.o

sources/timeleft.i: sources/timeleft.cpp.i
.PHONY : sources/timeleft.i

# target to preprocess a source file
sources/timeleft.cpp.i:
	$(MAKE) -f CMakeFiles/tamagotchi.dir/build.make CMakeFiles/tamagotchi.dir/sources/timeleft.cpp.i
.PHONY : sources/timeleft.cpp.i

sources/timeleft.s: sources/timeleft.cpp.s
.PHONY : sources/timeleft.s

# target to generate assembly for a file
sources/timeleft.cpp.s:
	$(MAKE) -f CMakeFiles/tamagotchi.dir/build.make CMakeFiles/tamagotchi.dir/sources/timeleft.cpp.s
.PHONY : sources/timeleft.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tamagotchi"
	@echo "... sources/button.o"
	@echo "... sources/button.i"
	@echo "... sources/button.s"
	@echo "... sources/connexion.o"
	@echo "... sources/connexion.i"
	@echo "... sources/connexion.s"
	@echo "... sources/draw.o"
	@echo "... sources/draw.i"
	@echo "... sources/draw.s"
	@echo "... sources/showBMP.o"
	@echo "... sources/showBMP.i"
	@echo "... sources/showBMP.s"
	@echo "... sources/sql.o"
	@echo "... sources/sql.i"
	@echo "... sources/sql.s"
	@echo "... sources/tamagotchi.o"
	@echo "... sources/tamagotchi.i"
	@echo "... sources/tamagotchi.s"
	@echo "... sources/textinput.o"
	@echo "... sources/textinput.i"
	@echo "... sources/textinput.s"
	@echo "... sources/timeleft.o"
	@echo "... sources/timeleft.i"
	@echo "... sources/timeleft.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

